import type { NextPage } from "next";
import Head from "next/head";
import { Education } from "../components/Sections/Education";
import { Experience } from "../components/Sections/Experience";
import { Hobby } from "../components/Sections/Hobby";
import { Photo } from "../components/Photo/Photo";
import { Programming } from "../components/Sections/Programming";
import styled from "styled-components";

const CardContainer = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;

  @media only screen and (max-width: $big) {
    grid-template-columns: 1fr;
  }
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CardContainer>
        <Education />
        <Photo />
        <Programming />
        <Experience />
        <Hobby />
      </CardContainer>
    </>
  );
};

export default Home;
