import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Photo } from "../components/Photo";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <Photo />
      </div>
    </>
  );
};

export default Home;
