import type { NextPage } from "next";
import Head from "next/head";
import { Education } from "../../components/Sections/Education";
import { Experience } from "../../components/Sections/Experience";
import { Hobby } from "../../components/Sections/Hobby";
import { Photo } from "../../components/Photo/Photo";
import { Programming } from "../../components/Sections/Programming";
import styles from "../../styles/Home.module.scss";

export const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <Education />
        <Photo />
        <Programming />
        <Experience />
        <Hobby />
      </div>
    </>
  );
};
